#!/usr/bin/env python3
"""
Builds the single-file ollama-chat.html from the split sources in dev/.

Why this exists: ollama-chat.html is meant to be published as one portable
file (drag it anywhere, double-click, it works), but editing 2,000+ lines in
one file is painful. dev/ holds the same app split into a shell HTML file,
a stylesheet, and one JS file per feature area. This script inlines all of
those back into a single HTML file.

Usage:
    python3 build.py

Reads:  dev/app.html (+ whatever local styles.css / js/*.js it references)
Writes: ollama-chat.html (at the repo root, next to this script)

Only local, relative references are inlined -- http(s):// tags (the CDN
scripts for marked/KaTeX/DOMPurify) are left exactly as they are, since those
are meant to stay as CDN links rather than get vendored into the file.

No dependencies -- standard library only.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DEV_DIR = ROOT / 'dev'
SOURCE_HTML = DEV_DIR / 'app.html'
OUTPUT_HTML = ROOT / 'ollama-chat.html'

BANNER = (
    '<!-- AUTO-GENERATED by build.py from dev/ -- do not hand-edit this file.\n'
    '     Make changes in dev/app.html, dev/styles.css, or dev/js/*.js,\n'
    '     then re-run `python3 build.py` to regenerate this file. -->\n'
)

# Matches a local (non-http/https) <link rel="stylesheet" href="...">
LINK_RE = re.compile(
    r'<link\s+rel="stylesheet"\s+href="(?!https?://)([^"]+)"\s*/?>'
)
# Matches a local (non-http/https) <script src="..."></script>
SCRIPT_RE = re.compile(
    r'<script\s+src="(?!https?://)([^"]+)"\s*></script>'
)


def _read_local(rel_path):
    path = (DEV_DIR / rel_path).resolve()
    if DEV_DIR not in path.parents and path != DEV_DIR:
        sys.exit(f'Refusing to read outside dev/: {rel_path}')
    if not path.is_file():
        sys.exit(f'Referenced file not found: {path}')
    return path.read_text(encoding='utf-8')


def inline_stylesheets(html):
    def repl(match):
        rel_path = match.group(1)
        css = _read_local(rel_path)
        print(f'  inlining stylesheet: {rel_path}')
        return f'<style>\n{css.rstrip(chr(10))}\n</style>'

    return LINK_RE.sub(repl, html)


def inline_scripts(html):
    def repl(match):
        rel_path = match.group(1)
        js = _read_local(rel_path)
        print(f'  inlining script: {rel_path}')
        return f'<script>\n{js.rstrip(chr(10))}\n</script>'

    return SCRIPT_RE.sub(repl, html)


def main():
    if not SOURCE_HTML.is_file():
        sys.exit(f'Missing {SOURCE_HTML} -- run this from the repo root.')

    print(f'Reading {SOURCE_HTML.relative_to(ROOT)}...')
    html = SOURCE_HTML.read_text(encoding='utf-8')

    print('Inlining local stylesheets...')
    html = inline_stylesheets(html)

    print('Inlining local scripts (CDN <script src> tags are left as-is)...')
    html = inline_scripts(html)

    html = BANNER + html

    OUTPUT_HTML.write_text(html, encoding='utf-8')
    print(f'Wrote {OUTPUT_HTML.relative_to(ROOT)} ({len(html.splitlines())} lines).')


if __name__ == '__main__':
    main()
